### ISSUE TITLE
Quase perdendo o prazo da v0.1

### ISSUE THREAD

**Issue by drbeco** [thaynamorim/discreta12melhorgrupo#2]
Adicionar milestone v0.1, completar a fase inicial,
completar (abrir) os 30 issues iniciais (5 de cada milestone), etc., etc., etc., conforme explicado em sala, até a meia-noite de hoje, e lançar release v0.1.

**Comment by canejo12** [comment]
Release lançada e milestone fechado.

**Comment by drbeco** [comment]
Parabéns aos dois pelo trabalho!
