### ISSUE TITLE
Branch remoto develop

### ISSUE THREAD

**Issue by drbeco** [thaynamorim/discreta12melhorgrupo#5]
Não está criado. Precisa criar.

**Comment by thaynamorim** [comment]
Está criado, Ruben. Ele só aparece quando já foi dado algum commit na develop. Também foram adicionados featues para cada membro do grupo.

**Comment by drbeco** [comment]
Thayná, não é assim que funciona, desculpe, mas você está enganada.

Você deve ter criado o `develop` como ramo local, e não remoto. Quer ter certeza? Digite:

`$ git remote show origin`

Veja se aparece:

```
 Remote branch:
    master tracked
    develop tracked
```

Estou reabrindo.

**Comment by thaynamorim** [comment]
Professor, não sei copiar bonito como o senhor: 
tmmdbb@hydra:~/discreta/rascunhos/discreta12melhorgrupo$ git remote show origin
 remote origin
  Fetch URL: https://github.com/thaynamorim/discreta12melhorgrupo.git
  Push  URL: https://github.com/thaynamorim/discreta12melhorgrupo.git
  HEAD branch: master
  Remote branches:
    develop tracked
    master  tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local refs configured for 'git push':
    develop pushes to develop (up to date)
    master  pushes to master  (up to date)
tmmdbb@hydra:~/discreta/rascunhos/discreta12melhorgrupo$

**Comment by drbeco** [comment]
Perfeito. (Mas eu tinha olhado lá antes de postar! rs rs). 

Bom que já resolveu.

Bug fechado. :ok_hand: 

---

Sobre copiar bonito, use três acentos graves antes e três depois:

```
beco@hydra:/home/tmmdbb/discreta/rascunhos/discreta12melhorgrupo$ git remote show origin
* remote origin
  Fetch URL: https://github.com/thaynamorim/discreta12melhorgrupo.git
  Push  URL: https://github.com/thaynamorim/discreta12melhorgrupo.git
  HEAD branch: master
  Remote branch:
    master tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (up to date)
beco@hydra:/home/tmmdbb/discreta/rascunhos/discreta12melhorgrupo$ 
```

Também pode colar imagem diretamente:

![ramo-develop](https://cloud.githubusercontent.com/assets/5805111/11580215/ba91ea98-9a13-11e5-871c-1d4a84b500cb.png)

Recomendo ler as opções de formatação **Markdown** no link logo acima dessa janelinha de edição:

**Styling with Markdown is supported**

Link:

https://guides.github.com/features/mastering-markdown/

**Comment by thaynamorim** [comment]
Não colei porque o senhor disse uma vez em sala que reportar erros não era a maneira correta via imagens. Obrigada pela atenção professor, boa noite

**Comment by drbeco** [comment]
Disse sim, e reafirmo. (Apesar de que neste caso você não estava reportando o erro, estava questionando o erro que eu estava reportando, insistindo que não havia nada errado). Em todo caso, ao perguntar sobre como "copiar bonito" eu respondi mostrando as opções do github (sim, ele aceita um "ctrl-V" de uma imagem, aceita emojis, e a formatação de código).

Nunca reporte erros com imagens, em especial (principalmente) por email. Principalmente quando há compilação envolvida para se descobrir o erro, e quando copiar e colar o próprio texto ou comandos pode ajudar a quem vai tentar descobrir o erro. Ou fazer uma busca no texto pode ajudar (cntrl-f em editores normais, `\` no `vi`) (Não dá para colar o comando de uma imagem, mas dá para colar de um texto como por exemplo se você selecionar ali: `git remote show origin`).

Enfim, obrigado pelo boa noite, mas ainda tenho muito trabalho, infelizmente. Em todo caso, agradeço!
