### ISSUE TITLE
Milestones com datas erradas?

### ISSUE THREAD

**Issue by drbeco** [thaynamorim/discreta12melhorgrupo#8]
Parece que os milestones estão com um dia de erro nas datas.

Por exemplo, a v0.1 deveria estar no prazo ainda hoje (dia 3) mas está dizendo que está atrasada!

![image](https://cloud.githubusercontent.com/assets/5805111/11579911/e5e15eac-9a10-11e5-9657-9e57ad48a16e.png)

A v0.2 é para dia 6, ali está dia 5. A seguinte é para dia 9. Conferir todas.

**Comment by thaynamorim** [comment]
Corrijido.
